version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BigBeerStrong2024
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume:
