<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
    <ProjectReference Include="..\WebApp\WebApp.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5c24d0dd-3c7a-4970-ac64-ce0b89bc6473</UserSecretsId>
  </PropertyGroup>

</Project>
