// <auto-generated />
using System;
using BigBeerData.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BigBeerData.Shared.Migrations
{
    [DbContext(typeof(BigBeerContext))]
    [Migration("20210426110105_calcCol")]
    partial class CalcCol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BigBeerData.Shared.Beer", b =>
                {
                    b.Property<int>("Bid")
                        .HasColumnType("int");

                    b.Property<double>("ABV")
                        .HasColumnType("float");

                    b.Property<string>("BaseStyle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("(case when charindex(' - ',[Style])=(0) then [Style] else rtrim(left([Style],charindex(' - ',[Style]))) end)");

                    b.Property<string>("BeerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeerPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrewerId")
                        .HasColumnType("int");

                    b.Property<string>("SLUG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bid");

                    b.HasIndex("BrewerId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerColour", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Hex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BeerColour");

                    b.HasData(
                        new
                        {
                            ID = 0,
                            Hex = "#FFFFFF"
                        },
                        new
                        {
                            ID = 1,
                            Hex = "#F8F4B4"
                        },
                        new
                        {
                            ID = 2,
                            Hex = "#F9E06C"
                        },
                        new
                        {
                            ID = 3,
                            Hex = "#F4CE51"
                        },
                        new
                        {
                            ID = 4,
                            Hex = "#F2BE37"
                        },
                        new
                        {
                            ID = 5,
                            Hex = "#EDAC1E"
                        },
                        new
                        {
                            ID = 6,
                            Hex = "#E59C19"
                        },
                        new
                        {
                            ID = 7,
                            Hex = "#DF8F16"
                        },
                        new
                        {
                            ID = 8,
                            Hex = "#D68019"
                        },
                        new
                        {
                            ID = 9,
                            Hex = "#CF731C"
                        },
                        new
                        {
                            ID = 10,
                            Hex = "#BD591B"
                        },
                        new
                        {
                            ID = 11,
                            Hex = "#C3621B"
                        },
                        new
                        {
                            ID = 12,
                            Hex = "#C86B1B"
                        },
                        new
                        {
                            ID = 13,
                            Hex = "#C05727"
                        },
                        new
                        {
                            ID = 14,
                            Hex = "#AD4417"
                        },
                        new
                        {
                            ID = 15,
                            Hex = "#AE4818"
                        },
                        new
                        {
                            ID = 16,
                            Hex = "#AD4417"
                        },
                        new
                        {
                            ID = 17,
                            Hex = "#A73D15"
                        },
                        new
                        {
                            ID = 18,
                            Hex = "#A23A15"
                        },
                        new
                        {
                            ID = 19,
                            Hex = "#9D3414"
                        },
                        new
                        {
                            ID = 20,
                            Hex = "#983015"
                        },
                        new
                        {
                            ID = 21,
                            Hex = "#932A14"
                        },
                        new
                        {
                            ID = 22,
                            Hex = "#8D2615"
                        },
                        new
                        {
                            ID = 23,
                            Hex = "#892515"
                        },
                        new
                        {
                            ID = 24,
                            Hex = "#832212"
                        },
                        new
                        {
                            ID = 25,
                            Hex = "#7D200F"
                        },
                        new
                        {
                            ID = 26,
                            Hex = "#771E0E"
                        },
                        new
                        {
                            ID = 27,
                            Hex = "#731C0B"
                        },
                        new
                        {
                            ID = 28,
                            Hex = "#70180C"
                        },
                        new
                        {
                            ID = 29,
                            Hex = "#6A160C"
                        },
                        new
                        {
                            ID = 30,
                            Hex = "#67120B"
                        },
                        new
                        {
                            ID = 31,
                            Hex = "#63100A"
                        },
                        new
                        {
                            ID = 32,
                            Hex = "#5F0E0A"
                        },
                        new
                        {
                            ID = 33,
                            Hex = "#5B0B0A"
                        },
                        new
                        {
                            ID = 34,
                            Hex = "#58080B"
                        },
                        new
                        {
                            ID = 35,
                            Hex = "#53080C"
                        },
                        new
                        {
                            ID = 36,
                            Hex = "#4B090B"
                        },
                        new
                        {
                            ID = 37,
                            Hex = "#470D0C"
                        },
                        new
                        {
                            ID = 38,
                            Hex = "#400C0E"
                        },
                        new
                        {
                            ID = 39,
                            Hex = "#3C0B0E"
                        },
                        new
                        {
                            ID = 40,
                            Hex = "#240A0B"
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerFamily", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("BeerTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BeerTypeID");

                    b.ToTable("BeerFamily");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BeerTypeID = 1,
                            Name = "Wheat Beer"
                        },
                        new
                        {
                            ID = 2,
                            BeerTypeID = 1,
                            Name = "Lambic and Sour Ale"
                        },
                        new
                        {
                            ID = 3,
                            BeerTypeID = 1,
                            Name = "Belgian Ale"
                        },
                        new
                        {
                            ID = 4,
                            BeerTypeID = 1,
                            Name = "Pale Ale"
                        },
                        new
                        {
                            ID = 5,
                            BeerTypeID = 1,
                            Name = "English Bitter"
                        },
                        new
                        {
                            ID = 6,
                            BeerTypeID = 1,
                            Name = "Scottish Ale"
                        },
                        new
                        {
                            ID = 7,
                            BeerTypeID = 1,
                            Name = "Brown Ale"
                        },
                        new
                        {
                            ID = 8,
                            BeerTypeID = 1,
                            Name = "Porter"
                        },
                        new
                        {
                            ID = 9,
                            BeerTypeID = 1,
                            Name = "Stout"
                        },
                        new
                        {
                            ID = 10,
                            BeerTypeID = 2,
                            Name = "Pilsner"
                        },
                        new
                        {
                            ID = 11,
                            BeerTypeID = 2,
                            Name = "American Lager"
                        },
                        new
                        {
                            ID = 12,
                            BeerTypeID = 2,
                            Name = "European Lager"
                        },
                        new
                        {
                            ID = 13,
                            BeerTypeID = 2,
                            Name = "Bock"
                        },
                        new
                        {
                            ID = 14,
                            BeerTypeID = 3,
                            Name = "Alt"
                        },
                        new
                        {
                            ID = 15,
                            BeerTypeID = 3,
                            Name = "French Ale"
                        },
                        new
                        {
                            ID = 16,
                            BeerTypeID = 3,
                            Name = "German Amber Ale"
                        },
                        new
                        {
                            ID = 17,
                            BeerTypeID = 3,
                            Name = "American Special"
                        },
                        new
                        {
                            ID = 18,
                            BeerTypeID = 3,
                            Name = "Smoked Beer"
                        },
                        new
                        {
                            ID = 19,
                            BeerTypeID = 3,
                            Name = "Barleywine"
                        },
                        new
                        {
                            ID = 20,
                            BeerTypeID = 3,
                            Name = "Strong Ale"
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerStyle", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<double>("ABVHigh")
                        .HasColumnType("float");

                    b.Property<double>("ABVLow")
                        .HasColumnType("float");

                    b.Property<int>("FamilyID")
                        .HasColumnType("int");

                    b.Property<double>("FinalGravHigh")
                        .HasColumnType("float");

                    b.Property<double>("FinalGravLow")
                        .HasColumnType("float");

                    b.Property<double>("IBUHigh")
                        .HasColumnType("float");

                    b.Property<double>("IBULow")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrigGravHigh")
                        .HasColumnType("float");

                    b.Property<double>("OrigGravLow")
                        .HasColumnType("float");

                    b.Property<int>("SRMHighID")
                        .HasColumnType("int");

                    b.Property<int>("SRMLowID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<int>("YeastID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("SRMHighID");

                    b.HasIndex("SRMLowID");

                    b.HasIndex("TypeID");

                    b.HasIndex("YeastID");

                    b.ToTable("BeerStyle");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ABVHigh = 3.6000000000000001,
                            ABVLow = 2.5,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 12.0,
                            IBULow = 3.0,
                            Name = "Berliner Weisse",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 4,
                            SRMLowID = 2,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 2,
                            ABVHigh = 6.4000000000000004,
                            ABVLow = 4.7000000000000002,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 5.0,
                            Name = "Lambic",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 15,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 3,
                            ABVHigh = 9.0,
                            ABVLow = 7.0,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 35.0,
                            IBULow = 25.0,
                            Name = "Belgian Gold Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 6,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 4,
                            ABVHigh = 5.5,
                            ABVLow = 4.5,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 28.0,
                            IBULow = 15.0,
                            Name = "Belgian White",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 4,
                            SRMLowID = 2,
                            TypeID = 1,
                            YeastID = 2
                        },
                        new
                        {
                            ID = 5,
                            ABVHigh = 6.4000000000000004,
                            ABVLow = 4.7000000000000002,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 5.0,
                            Name = "Gueuze",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 15,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 6,
                            ABVHigh = 10.0,
                            ABVLow = 7.0,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Tripel",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 7,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 7,
                            ABVHigh = 5.0,
                            ABVLow = 3.5,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 20.0,
                            IBULow = 5.0,
                            Name = "American Wheat",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 8,
                            SRMLowID = 2,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 8,
                            ABVHigh = 5.5,
                            ABVLow = 4.5,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 5.0,
                            Name = "Faro",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 15,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 9,
                            ABVHigh = 8.0999999999999996,
                            ABVLow = 4.5,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 25.0,
                            Name = "Saison",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 10,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 10,
                            ABVHigh = 5.5,
                            ABVLow = 4.5,
                            FamilyID = 4,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "Pale Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 11,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 11,
                            ABVHigh = 4.5,
                            ABVLow = 2.8999999999999999,
                            FamilyID = 11,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 8.0,
                            Name = "American Lite",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 4,
                            SRMLowID = 2,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 12,
                            ABVHigh = 5.5999999999999996,
                            ABVLow = 4.5,
                            FamilyID = 12,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 18.0,
                            Name = "Munich Helles",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 5,
                            SRMLowID = 3,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 13,
                            ABVHigh = 7.5,
                            ABVLow = 6.0,
                            FamilyID = 13,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 35.0,
                            IBULow = 20.0,
                            Name = "Helles Bock",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 10,
                            SRMLowID = 4,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 14,
                            ABVHigh = 5.5999999999999996,
                            ABVLow = 4.2999999999999998,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 8.0,
                            Name = "Weizenbier",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 9,
                            SRMLowID = 3,
                            TypeID = 1,
                            YeastID = 2
                        },
                        new
                        {
                            ID = 15,
                            ABVHigh = 7.0,
                            ABVLow = 4.7000000000000002,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 21.0,
                            IBULow = 15.0,
                            Name = "Fruit Beer",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 0,
                            SRMLowID = 0,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 16,
                            ABVHigh = 5.5999999999999996,
                            ABVLow = 3.8999999999999999,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 35.0,
                            IBULow = 20.0,
                            Name = "Belgian Pale Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 17,
                            ABVHigh = 5.7000000000000002,
                            ABVLow = 4.5,
                            FamilyID = 4,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "American Pale Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 11,
                            SRMLowID = 4,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 18,
                            ABVHigh = 3.7999999999999998,
                            ABVLow = 3.0,
                            FamilyID = 5,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 335.0,
                            IBULow = 20.0,
                            Name = "Ordinary Bitter",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 12,
                            SRMLowID = 6,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 19,
                            ABVHigh = 4.0,
                            ABVLow = 2.7999999999999998,
                            FamilyID = 6,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 20.0,
                            IBULow = 9.0,
                            Name = "Scottish Light 60/-",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 17,
                            SRMLowID = 8,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 20,
                            ABVHigh = 4.0999999999999996,
                            ABVLow = 2.5,
                            FamilyID = 7,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 24.0,
                            IBULow = 10.0,
                            Name = "English Mid",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 25,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 21,
                            ABVHigh = 5.5,
                            ABVLow = 3.2000000000000002,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 50.0,
                            IBULow = 30.0,
                            Name = "Dry Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 22,
                            ABVHigh = 7.5,
                            ABVLow = 5.0,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 70.0,
                            IBULow = 35.0,
                            Name = "Foreign Extra Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 23,
                            ABVHigh = 5.4000000000000004,
                            ABVLow = 4.5999999999999996,
                            FamilyID = 10,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 45.0,
                            IBULow = 25.0,
                            Name = "German Pilsner",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 4,
                            SRMLowID = 2,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 24,
                            ABVHigh = 4.7999999999999998,
                            ABVLow = 4.0999999999999996,
                            FamilyID = 11,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 17.0,
                            IBULow = 5.0,
                            Name = "American Standard",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 6,
                            SRMLowID = 2,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 25,
                            ABVHigh = 6.0999999999999996,
                            ABVLow = 5.0999999999999996,
                            FamilyID = 12,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 29.0,
                            IBULow = 23.0,
                            Name = "Dortmunder",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 6,
                            SRMLowID = 4,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 26,
                            ABVHigh = 7.9000000000000004,
                            ABVLow = 6.5999999999999996,
                            FamilyID = 13,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Doppelbock",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 30,
                            SRMLowID = 12,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 27,
                            ABVHigh = 6.0,
                            ABVLow = 4.5,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 15.0,
                            IBULow = 10.0,
                            Name = "Dunkelwiezen",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 23,
                            SRMLowID = 17,
                            TypeID = 1,
                            YeastID = 2
                        },
                        new
                        {
                            ID = 28,
                            ABVHigh = 5.7999999999999998,
                            ABVLow = 4.0,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 14.0,
                            Name = "Flanders red",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 16,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 29,
                            ABVHigh = 12.0,
                            ABVLow = 7.0,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 25.0,
                            Name = "Belgian Dark Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 20,
                            SRMLowID = 7,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 30,
                            ABVHigh = 7.5999999999999996,
                            ABVLow = 5.0999999999999996,
                            FamilyID = 4,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 60.0,
                            IBULow = 40.0,
                            Name = "India Pale Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 8,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 31,
                            ABVHigh = 4.7999999999999998,
                            ABVLow = 3.7000000000000002,
                            FamilyID = 5,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 25.0,
                            Name = "Special Bitter",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 12,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 32,
                            ABVHigh = 4.0999999999999996,
                            ABVLow = 3.5,
                            FamilyID = 6,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 12.0,
                            Name = "Scottish Heavy 70/-",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 19,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 33,
                            ABVHigh = 6.0,
                            ABVLow = 4.2000000000000002,
                            FamilyID = 7,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 60.0,
                            IBULow = 25.0,
                            Name = "American Brown",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 22,
                            SRMLowID = 15,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 34,
                            ABVHigh = 5.2000000000000002,
                            ABVLow = 3.7999999999999998,
                            FamilyID = 8,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 35.0,
                            IBULow = 20.0,
                            Name = "Brown Porter",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 35,
                            SRMLowID = 20,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 35,
                            ABVHigh = 6.4000000000000004,
                            ABVLow = 3.2000000000000002,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "Sweet Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 36,
                            ABVHigh = 9.0,
                            ABVLow = 7.7999999999999998,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 80.0,
                            IBULow = 50.0,
                            Name = "Imperial Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 37,
                            ABVHigh = 5.0999999999999996,
                            ABVLow = 4.0999999999999996,
                            FamilyID = 10,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 45.0,
                            IBULow = 35.0,
                            Name = "Bohemian Pilsner",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 5,
                            SRMLowID = 3,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 38,
                            ABVHigh = 5.0999999999999996,
                            ABVLow = 4.5999999999999996,
                            FamilyID = 11,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 23.0,
                            IBULow = 13.0,
                            Name = "American Premium",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 8,
                            SRMLowID = 2,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 39,
                            ABVHigh = 5.4000000000000004,
                            ABVLow = 4.7999999999999998,
                            FamilyID = 12,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 16.0,
                            Name = "Munich Dunkel",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 23,
                            SRMLowID = 17,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 40,
                            ABVHigh = 7.5999999999999996,
                            ABVLow = 6.4000000000000004,
                            FamilyID = 13,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Traditional Bock",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 30,
                            SRMLowID = 15,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 41,
                            ABVHigh = 9.5999999999999996,
                            ABVLow = 6.5,
                            FamilyID = 1,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 15.0,
                            Name = "Wiezenbock",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 30,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 2
                        },
                        new
                        {
                            ID = 42,
                            ABVHigh = 6.5,
                            ABVLow = 4.0,
                            FamilyID = 2,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 14.0,
                            Name = "Oud bruin",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 20,
                            SRMLowID = 12,
                            TypeID = 1,
                            YeastID = 1
                        },
                        new
                        {
                            ID = 43,
                            ABVHigh = 8.0,
                            ABVLow = 3.2000000000000002,
                            FamilyID = 3,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 20.0,
                            Name = "Dubbel",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 20,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 44,
                            ABVHigh = 5.7000000000000002,
                            ABVLow = 4.5,
                            FamilyID = 4,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "American Amber Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 18,
                            SRMLowID = 11,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 45,
                            ABVHigh = 4.5999999999999996,
                            ABVLow = 3.7000000000000002,
                            FamilyID = 5,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 45.0,
                            IBULow = 30.0,
                            Name = "Extraspecial Bitter",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 12,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 46,
                            ABVHigh = 4.9000000000000004,
                            ABVLow = 4.0,
                            FamilyID = 6,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 36.0,
                            IBULow = 15.0,
                            Name = "Scottish Export 80/-",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 19,
                            SRMLowID = 10,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 47,
                            ABVHigh = 6.0,
                            ABVLow = 3.5,
                            FamilyID = 7,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 25.0,
                            IBULow = 15.0,
                            Name = "English Brown",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 30,
                            SRMLowID = 15,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 48,
                            ABVHigh = 6.0,
                            ABVLow = 4.7999999999999998,
                            FamilyID = 8,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 30.0,
                            Name = "Robust Porter",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 30,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 49,
                            ABVHigh = 6.0999999999999996,
                            ABVLow = 3.2999999999999998,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 50.0,
                            IBULow = 20.0,
                            Name = "Oatmeal Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 50,
                            ABVHigh = 12.0,
                            ABVLow = 8.0,
                            FamilyID = 9,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 90.0,
                            IBULow = 50.0,
                            Name = "Russian Imperial Stout",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 40,
                            TypeID = 1,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 51,
                            ABVHigh = 6.0,
                            ABVLow = 5.0,
                            FamilyID = 10,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "American Pilsner",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 6,
                            SRMLowID = 3,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 52,
                            ABVHigh = 5.5999999999999996,
                            ABVLow = 4.0999999999999996,
                            FamilyID = 11,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 20.0,
                            IBULow = 14.0,
                            Name = "American Dark",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 20,
                            SRMLowID = 10,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 53,
                            ABVHigh = 5.0,
                            ABVLow = 3.7999999999999998,
                            FamilyID = 12,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 22.0,
                            Name = "Schwarzbier",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 25,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 54,
                            ABVHigh = 14.4,
                            ABVLow = 8.6999999999999993,
                            FamilyID = 13,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 50.0,
                            IBULow = 25.0,
                            Name = "Eisbock",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 18,
                            TypeID = 2,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 55,
                            ABVHigh = 5.2000000000000002,
                            ABVLow = 4.7999999999999998,
                            FamilyID = 14,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Kolsch",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 5,
                            SRMLowID = 4,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 56,
                            ABVHigh = 8.0,
                            ABVLow = 4.5,
                            FamilyID = 15,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Biere de garde",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 12,
                            SRMLowID = 5,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 57,
                            ABVHigh = 6.5,
                            ABVLow = 5.0999999999999996,
                            FamilyID = 16,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 18.0,
                            Name = "Oktoberfest",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 12,
                            SRMLowID = 7,
                            TypeID = 3,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 58,
                            ABVHigh = 6.0,
                            ABVLow = 4.5,
                            FamilyID = 17,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 35.0,
                            IBULow = 10.0,
                            Name = "Cream Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 8,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 59,
                            ABVHigh = 5.5,
                            ABVLow = 5.0,
                            FamilyID = 18,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 30.0,
                            IBULow = 20.0,
                            Name = "Smoked Beer",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 17,
                            SRMLowID = 12,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 60,
                            ABVHigh = 8.5,
                            ABVLow = 6.0999999999999996,
                            FamilyID = 20,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 30.0,
                            Name = "English Old (Strong) Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 16,
                            SRMLowID = 12,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 61,
                            ABVHigh = 5.0999999999999996,
                            ABVLow = 4.5999999999999996,
                            FamilyID = 14,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 48.0,
                            IBULow = 25.0,
                            Name = "Altbier",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 19,
                            SRMLowID = 11,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 62,
                            ABVHigh = 5.5,
                            ABVLow = 4.5999999999999996,
                            FamilyID = 16,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 28.0,
                            IBULow = 20.0,
                            Name = "Vienna",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 14,
                            SRMLowID = 8,
                            TypeID = 3,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 63,
                            ABVHigh = 5.0,
                            ABVLow = 3.6000000000000001,
                            FamilyID = 17,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 45.0,
                            IBULow = 35.0,
                            Name = "Steam Beer",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 17,
                            SRMLowID = 8,
                            TypeID = 3,
                            YeastID = 3
                        },
                        new
                        {
                            ID = 64,
                            ABVHigh = 12.199999999999999,
                            ABVLow = 8.4000000000000004,
                            FamilyID = 19,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 100.0,
                            IBULow = 50.0,
                            Name = "Bareleywine",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 22,
                            SRMLowID = 14,
                            TypeID = 3,
                            YeastID = 4
                        },
                        new
                        {
                            ID = 65,
                            ABVHigh = 9.0,
                            ABVLow = 6.0,
                            FamilyID = 20,
                            FinalGravHigh = 0.0,
                            FinalGravLow = 0.0,
                            IBUHigh = 40.0,
                            IBULow = 20.0,
                            Name = "Strong \"Scotch\" Ale",
                            OrigGravHigh = 0.0,
                            OrigGravLow = 0.0,
                            SRMHighID = 40,
                            SRMLowID = 10,
                            TypeID = 3,
                            YeastID = 4
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerType", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BeerType");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Ale"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Lager"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Mixed"
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerYeast", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("BaseColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BeerYeast");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BaseColour = "#775323",
                            Name = "Ale yeast with lactic bacteria"
                        },
                        new
                        {
                            ID = 2,
                            BaseColour = "#8E221F",
                            Name = "Wheat ale yeast"
                        },
                        new
                        {
                            ID = 3,
                            BaseColour = "#0A3D72",
                            Name = "Ale yeast"
                        },
                        new
                        {
                            ID = 4,
                            BaseColour = "#227547",
                            Name = "Lager yeast"
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.Brewer", b =>
                {
                    b.Property<int>("BrewerId")
                        .HasColumnType("int");

                    b.Property<string>("BrewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("SLUG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrewerId");

                    b.ToTable("Brewers");
                });

            modelBuilder.Entity("BigBeerData.Shared.Checkin", b =>
                {
                    b.Property<double>("CheckinId")
                        .HasColumnType("float");

                    b.Property<int>("Bid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("CheckinId");

                    b.HasIndex("Bid");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("BigBeerData.Shared.Establishment", b =>
                {
                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<int>("BaseZoom")
                        .HasColumnType("int");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastCheckinUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<bool>("MaxedCheckinHistory")
                        .HasColumnType("bit");

                    b.HasKey("EstablishmentId");

                    b.HasIndex("LocationId");

                    b.ToTable("Establishments");

                    b.HasData(
                        new
                        {
                            EstablishmentId = 28351,
                            BaseZoom = 17,
                            EstablishmentName = "Archive Beer Boutique",
                            Lat = -27.479199999999999,
                            LocationId = 1,
                            Long = 153.01300000000001,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 1332593,
                            BaseZoom = 17,
                            EstablishmentName = "Bitter Phew",
                            Lat = -33.879899999999999,
                            LocationId = 3,
                            Long = 151.21600000000001,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 1398768,
                            BaseZoom = 15,
                            EstablishmentName = "Brewski",
                            Lat = -27.464500000000001,
                            LocationId = 1,
                            Long = 153.01300000000001,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 2221333,
                            BaseZoom = 17,
                            EstablishmentName = "Malt Traders",
                            Lat = -27.4697,
                            LocationId = 1,
                            Long = 153.03,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 3323017,
                            BaseZoom = 17,
                            EstablishmentName = "Mr Edward's Alehouse",
                            Lat = -27.471399999999999,
                            LocationId = 1,
                            Long = 153.03,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 3831964,
                            BaseZoom = 17,
                            EstablishmentName = "Saccharomyces Beer Cafe",
                            Lat = -27.474499999999999,
                            LocationId = 1,
                            Long = 153.017,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 4221968,
                            BaseZoom = 17,
                            EstablishmentName = "Tippler's Tap Southbank",
                            Lat = -27.4801,
                            LocationId = 1,
                            Long = 153.023,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 4308714,
                            BaseZoom = 18,
                            EstablishmentName = "The Noble Hops",
                            Lat = -33.892699999999998,
                            LocationId = 3,
                            Long = 151.202,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 6066172,
                            BaseZoom = 17,
                            EstablishmentName = "Malt Traders - Southbank",
                            Lat = -27.479900000000001,
                            LocationId = 1,
                            Long = 153.023,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 7767345,
                            BaseZoom = 17,
                            EstablishmentName = "Tippler's Tap",
                            Lat = -27.457899999999999,
                            LocationId = 1,
                            Long = 153.042,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 7918310,
                            BaseZoom = 17,
                            EstablishmentName = "Hellbound",
                            Lat = -27.464500000000001,
                            LocationId = 1,
                            Long = 153.042,
                            MaxedCheckinHistory = false
                        },
                        new
                        {
                            EstablishmentId = 9136453,
                            BaseZoom = 17,
                            EstablishmentName = "The Woods Bar",
                            Lat = -27.411999999999999,
                            LocationId = 4,
                            Long = 152.97499999999999,
                            MaxedCheckinHistory = false
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Brisbane"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Melbourne"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Sydney"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Outer Brisbane"
                        });
                });

            modelBuilder.Entity("BigBeerData.Shared.Beer", b =>
                {
                    b.HasOne("BigBeerData.Shared.Brewer", "Brewer")
                        .WithMany("Beers")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerFamily", b =>
                {
                    b.HasOne("BigBeerData.Shared.BeerType", "Type")
                        .WithMany("Families")
                        .HasForeignKey("BeerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerStyle", b =>
                {
                    b.HasOne("BigBeerData.Shared.BeerFamily", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BigBeerData.Shared.BeerColour", "SRMHigh")
                        .WithMany("HighStyles")
                        .HasForeignKey("SRMHighID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BigBeerData.Shared.BeerColour", "SRMLow")
                        .WithMany("LowStyles")
                        .HasForeignKey("SRMLowID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BigBeerData.Shared.BeerType", "Type")
                        .WithMany("Styles")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BigBeerData.Shared.BeerYeast", "Yeast")
                        .WithMany("Styles")
                        .HasForeignKey("YeastID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("SRMHigh");

                    b.Navigation("SRMLow");

                    b.Navigation("Type");

                    b.Navigation("Yeast");
                });

            modelBuilder.Entity("BigBeerData.Shared.Checkin", b =>
                {
                    b.HasOne("BigBeerData.Shared.Beer", "Beer")
                        .WithMany("Checkins")
                        .HasForeignKey("Bid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BigBeerData.Shared.Establishment", "Establishment")
                        .WithMany("Checkins")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("BigBeerData.Shared.Establishment", b =>
                {
                    b.HasOne("BigBeerData.Shared.Location", "Location")
                        .WithMany("Establishments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BigBeerData.Shared.Beer", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerColour", b =>
                {
                    b.Navigation("HighStyles");

                    b.Navigation("LowStyles");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerType", b =>
                {
                    b.Navigation("Families");

                    b.Navigation("Styles");
                });

            modelBuilder.Entity("BigBeerData.Shared.BeerYeast", b =>
                {
                    b.Navigation("Styles");
                });

            modelBuilder.Entity("BigBeerData.Shared.Brewer", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("BigBeerData.Shared.Establishment", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("BigBeerData.Shared.Location", b =>
                {
                    b.Navigation("Establishments");
                });
#pragma warning restore 612, 618
        }
    }
}
